<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-5VBKCKK" failures="1" tests="16" name="com.mk.testcases.DashboardTest" time="38.662" errors="0" timestamp="2024-11-07T22:10:35 IST" skipped="0">
  <testcase classname="com.mk.testcases.DashboardTest" name="TC_10" time="3.830"/>
  <testcase classname="com.mk.testcases.DashboardTest" name="TC_13" time="0.837">
    <failure message="False: not clicked on My leave button did not expect to find [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: False: not clicked on My leave button did not expect to find [true] but found [false]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:969)
at org.testng.Assert.assertTrue(Assert.java:43)
at com.mk.testcases.DashboardTest.TC_13(DashboardTest.java:109)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:584)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:172)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:804)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:145)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at org.testng.TestRunner.privateRun(TestRunner.java:770)
at org.testng.TestRunner.run(TestRunner.java:591)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:402)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:396)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:355)
at org.testng.SuiteRunner.run(SuiteRunner.java:304)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1180)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1102)
at org.testng.TestNG.runSuites(TestNG.java:1032)
at org.testng.TestNG.run(TestNG.java:1000)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
    </failure>
  </testcase> <!-- TC_13 -->
  <testcase classname="com.mk.testcases.DashboardTest" name="TC_4" time="1.602"/>
  <testcase classname="com.mk.testcases.DashboardTest" name="TC_12" time="1.565"/>
  <testcase classname="com.mk.testcases.DashboardTest" name="TC_6" time="1.712"/>
  <testcase classname="com.mk.testcases.DashboardTest" name="TC_9" time="2.205"/>
  <testcase classname="com.mk.testcases.DashboardTest" name="TC_11" time="4.814"/>
  <testcase classname="com.mk.testcases.DashboardTest" name="TC_3" time="3.939"/>
  <testcase classname="com.mk.testcases.DashboardTest" name="TC_15" time="3.582"/>
  <testcase classname="com.mk.testcases.DashboardTest" name="TC_1" time="1.645"/>
  <testcase classname="com.mk.testcases.DashboardTest" name="TC_8" time="2.168"/>
  <testcase classname="com.mk.testcases.DashboardTest" name="TC_14" time="2.605"/>
  <testcase classname="com.mk.testcases.DashboardTest" name="TC_5" time="2.700"/>
  <testcase classname="com.mk.testcases.DashboardTest" name="TC_2" time="1.639"/>
  <testcase classname="com.mk.testcases.DashboardTest" name="TC_16" time="1.498"/>
  <testcase classname="com.mk.testcases.DashboardTest" name="TC_7" time="2.321"/>
</testsuite> <!-- com.mk.testcases.DashboardTest -->
